# Site settings
title: Mehul Singh
description: This is Mehul's personal portfolio. He is a bachelor's student majoring in Computer Science and is preparing for his cybersecurity certifications.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mehul Singh
user_description: Mehul is a bachelor's student majoring in cybersecurity, who is currently preparing for his OSCP certification. He writes writeups for Hackthebox machines and during his free time is a photographer and a gamer. He's looking for internship/job opportunities in the cybersecurity domain to enhance his real-life experience and become an even better penetration-tester.
user_title: Security+ | NSE | CNSS
email: singhmehul@hotmail.com
twitter_username: 0x__shell
github_username: xmehulx
buymeacoffee_username: xmehulx

# Google-analytics
google-analytics:
  id: "UA-164500584-1"

exclude: ['package.json', 'src' , 'node_modules']
