# Site settings
title: Mehul Singh
description: This is Mehul's personal portfolio. He is a graduate student majoring in IT Security and is preparing for his cybersecurity certifications.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mehul Singh
user_description: Mehul is a graduate student majoring in Computer Engineering and IT Security, who is currently preparing for his red/blue team certifications. He is a security blogger who also writes writeups for CTF challenges and during his free time is a photographer and a gamer. He's looking for full-time opportunities in the cybersecurity domain to apply his real-life experience and further his experience to become an even better security practitioner.
user_title: GRC Advisor | Security Analyst 
email: singhmehul@hotmail.com
twitter_username: 0x__shell
github_username: xmehulx
buymeacoffee_username: xmehulx

# Google-analytics
google-analytics:
  id: "UA-164500584-1"

exclude: ['package.json', 'src' , 'node_modules']
